apiVersion: apps/v1
kind: Deployment
metadata:
  name: web4-cloud
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web4-cloud
  template:
    metadata:
      labels:
        app: web4-cloud
    spec:
      containers:
        - name: web4-cloud
          image: kubuverse/web4-cloud:latest
          env:
            - name: ETH_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: web4-secrets
                  key: eth_rpc_url
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: web4-secrets
                  key: private_key
            - name: CONFIG_JSON
              value: '{"max_concurrency":3,"max_retries":2}'
          ports:
            - containerPort: 5454
